### ISSUE TITLE
Connect-AzureAD requires elevated shell when authenticating with a service principal and certificate

### ISSUE THREAD

**Issue by benkd** [Azure/azure-docs-powershell-azuread#198]
Hello,

Not sure if this is intentional but it appears that an elevated shell is required to connect to AzureAD when using a service principal and certificate. Authenticating with `-AadAccessToken` and `-AccountId` works fine in a normal shell, as does logging in interactively with `Connect-AzureAD`.

I thought maybe when trying to retrieve to certificate thumbprint from the localmachine cert store, but that works fine as well without an elevated prompt.
Hopefully I'm just missing something on my end but thought I'd open a request anyways.

Thanks!
Here are the errors that I get:

```Connect-AzureAD -TenantId $tenantID -ApplicationId $applicationID -CertificateThumbprint $thumbprint
Connect-AzureAD : One or more errors occurred.
At line:5 char:1
+ Connect-AzureAD -TenantId $tenantID -ApplicationId $applicationID -Ce ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (:) [Connect-AzureAD], AggregateException
    + FullyQualifiedErrorId : Connect-AzureAD,Microsoft.Open.Azure.AD.CommonLibrary.ConnectAzureAD

Connect-AzureAD : Keyset does not exist

At line:5 char:1
+ Connect-AzureAD -TenantId $tenantID -ApplicationId $applicationID -Ce ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (:) [Connect-AzureAD], CryptographicException
    + FullyQualifiedErrorId : Connect-AzureAD,Microsoft.Open.Azure.AD.CommonLibrary.ConnectAzureAD

Connect-AzureAD : One or more errors occurred.
At line:5 char:1
+ Connect-AzureAD -TenantId $tenantID -ApplicationId $applicationID -Ce ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-AzureAD], AggregateException
    + FullyQualifiedErrorId : System.AggregateException,Microsoft.Open.Azure.AD.CommonLibrary.ConnectAzureAD```

**Comment by clownwilleatme** [comment]
Can confirm the exact same behaviour - thanks for the workaround of running as admin.

**Comment by rmbolger** [comment]
You don't need an elevated shell. You just need to give the account permission to read the private key which it doesn't have by default (unless you happen to be an admin with an elevated shell).

Here's a StackOverflow question that describes how to configure permissions for the NETWORK SERVICE account. But you can apply the information to any account or group that needs access.

https://stackoverflow.com/questions/46964941/service-fabric-authenticating-with-azure-keyvault-via-cert-keyset-does-not-ex

**Comment by andypturner** [comment]
If the certificate/private key is only going to be accessed by a single user (yourself or a service code running a scheduled task for example) then you can simply store them in the user's own personal certificate store to which that user has full rights. In fact if this is the case, I think I'd say that's more secure as it's not available to other users (at least, not as easily).

If you have a PFX of the cert/key and you're logged in as the user who's store you want to put it in then you can just double-click it to import.

However, if you're not currently logged in as the user who's store you want to add it to you can spin up a PowerShell prompt/ISE  session as the user (shift+right-click run as different user) then run the following (you can use this instead of double-clicking above too):

`$pwd = Read-Host -Prompt "Password" -AsSecureString
Import-PfxCertificate -FilePath C:\path\to\file\filename.pfx -CertStoreLocation Cert:\CurrentUser\My -Password $pwd`

**Comment by billmath** [comment]
This is resolved.
