### ISSUE TITLE
Set-MsolUser.md - Typo

### ISSUE THREAD

**Issue by dahager** [Azure/azure-docs-powershell-azuread#214]
azure-docs-powershell-azuread/azureadps-1.0/MSOnline/Set-MsolUser.md

I created a Pull request but it wasnt commited.
Please fix that typo:

_This command sets block credential to **$Tue** for a user, which blocks them from being able to sign in. This cannot be done for a synced user._

**Comment by billmath** [comment]
Hi @dahager 

Sorry for the delay in response.  I have opened a work item for this so that engineering can take a look and possibly address this.  Unfortunately, this needs to be corrected in the source code.  The cmdlt reference markdown files are auto-generated from the source, so any pull request to correct it would be overwritten the next time they are updated.  And the reference files should mirror the *.dll-help.xml file that is on the box.  At this point, I am going to go ahead and close this issue and will post any update I have here.  Thanks!

Bill
