### ISSUE TITLE
Connecting to Azure AD in a runspace-safe manner (no process- or disk-level caching)

### ISSUE THREAD

**Issue by KirkMunro** [Azure/azure-docs-powershell-azuread#229]
How does someone log in to Azure AD _without_ storing the profile in a static variable such that it is available across the process to every PowerShell runspace in a process? In Azure PowerShell, I can log in programmatically, and then identify the in-memory profile I want to use in each command I invoke, with no disk caching and no caching in static variables. I need to be able to do the same here, but Connect-AzureAD does not seem to have any options here, always caching the information such that it's available to every runspace in a process. This causes problems in many scenarios (any time you want to do automation against Azure PowerShell using separate runspaces in a single process to work with different Azure tenants).

Can this please be addressed? Login caching must be runspace-scoped or thread-scoped, not process-scoped.

**Comment by corydwood** [comment]
I second @KirkMunro's suggestion since I would like the ability to run AzureAD cmdlets against all of our Azure tenants using runspaces. I can do this with the AzureRM cmdlets because I can pass the correct context to the cmdlets using the **AzureRmContext** parameter.

Can we get a similar context option for the AzureAD cmdlets?

**Comment by robmcfeely** [comment]
This renders the module useless for a multi-tenant concurrent application.  Come on MS, that is mentioned no-where in your docs that I can see.  

Would appreciate someone from MS responding here!!

Any workarounds?

**Comment by adamedx** [comment]
Can't say I have great workarounds. Here's one idea:
1. Get an access token
2. Create N jobs via start-job that execute your parallel commands. Each job should be passed whatever parameters are required, along with the access token as a JWT string. The job scriptblock should start with `Connect-AzureAd` with the `AadAccessToken` parameter so that the job can authenticate. Since jobs are separate processes they can all happily call `Connect-AzureAd` at the same time.
3. Wait for all the jobs to complete.

This is sort of like @corydwood 's workaround, but it just continues to let you use the commands. And of course jobs are much heavier than threads / runspaces, but you can still spin up 100 or so of those without too much trouble.

**Comment by adamedx** [comment]
If anyone knows more about the failure mode, e.g. what happens today when you try to use runspaces (exception, auth failure, hang, etc), we might be able to devise a better workaround.

**Comment by billmath** [comment]
Hi @KirkMunro 

Thank you for your issue submission. Unfortunately, this appears to be a problem with the cmdlt and a support issue. Issues in this repo are for documentation issues. You can try one of the following links for additional help.

Microsoft Support: https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/

Bill
