### ISSUE TITLE
Connect-MsolService doesn't work with MSGraph authentication

### ISSUE THREAD

**Issue by XabiBeltza** [Azure/azure-docs-powershell-azuread#246]
I get a MSGraph token with the following code:
$AadModule = Get-Module -Name "AzureAD" -Verbose:$false
    if ($null -eq $AadModule)
    {
        Write-Error "Get-FHGraphAccessToken: AzureAD module was not loaded!"
    }
    $adal = Join-Path $AadModule.ModuleBase "Microsoft.IdentityModel.Clients.ActiveDirectory.dll"
    $adalforms = Join-Path $AadModule.ModuleBase "Microsoft.IdentityModel.Clients.ActiveDirectory.Platform.dll"
    [System.Reflection.Assembly]::LoadFrom($adal) | Out-Null
    [System.Reflection.Assembly]::LoadFrom($adalforms) | Out-Null
    $authority = "https://login.microsoftonline.com/$TenantName"
    $authContext = New-Object "Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext" -ArgumentList $authority
    $platformParameters = New-Object "Microsoft.IdentityModel.Clients.ActiveDirectory.PlatformParameters" -ArgumentList $CredPrompt
    if ($CredPrompt -eq "Auto")
    {
        $userUPN = "Redacted"
        Write-Verbose "Get-FHGraphAccessToken: Acquiring Graph token for user $userUPN ..."
        $userId = New-Object "Microsoft.IdentityModel.Clients.ActiveDirectory.UserIdentifier" -ArgumentList @($userUPN,2)
        $authResult = $authContext.AcquireTokenAsync($resourceAppIdURI, $clientId, $redirectUri, $platformParameters,$userId).Result
    }
    else 
    {
        Write-Verbose "Get-FHGraphAccessToken: Acquiring Graph token ..."
        $authResult = $authContext.AcquireTokenAsync($resourceAppIdURI, $clientId, $redirectUri, $platformParameters).Result
    }
    
    return $authResult

If I feed the resulting variable to the function:
Connect-MsolService -AzureEnvironment AzureCloud -MsGraphAccessToken $MSGraphToken
or
Connect-MsolService -AzureEnvironment AzureCloud -MsGraphAccessToken $MSGraphToken.AccessToken

It doesn't matter what I give to the parameter MsGraphAccessToken , I always get the following exception:

Connect-MsolService : The given key was not present in the dictionary.
At line:1 char:1
+ Connect-MsolService -MsGraphAccessToken $MSGraphToken.IdToken
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [Connect-MsolService], KeyNotFoundException
    + FullyQualifiedErrorId : System.Collections.Generic.KeyNotFoundException,Microsoft.Online.Administration.Automation.ConnectMsolService

**Comment by jsypkens** [comment]
@XabiBeltza I'm experiencing the same issue. Did you make any progress on this?

**Comment by jsypkens** [comment]
I figured out why this is broken. I decompiled the PowerShell command "Connect-MsolService" - here's a snippet in the authentication section:

```
UserSessionState.AccessTokens = new Dictionary<EndPointAlias, string>();
if (hasAdGraphAccessToken)
      UserSessionState.AccessTokens.Add(EndPointAlias.AzureAD, this.AdGraphAccessToken);
if (hasMsGraphAccessToken)
      UserSessionState.AccessTokens.Add(EndPointAlias.MSGraph, this.MsGraphAccessToken);

foreach (Claim claim in (new JwtSecurityToken(UserSessionState.AccessTokens[EndPointAlias.AzureAD])).Claims)

```

You can see that they're assigning AdGraphAccessToken to the AzureAD type in the AccessTokens dictionary, and the MsGraphAccessToken to the MSGraph type, but then immediately aftewards they're looping through claims from the AzureAD Dictionary object - and, of course, it throws an exception _"The given key was not present in the dictionary"_ because of course, it isn't in the dictionary... because we weren't using the AdGraphToken, we're using the MsGraphToken.

Side note, even using an AdGraphToken it _also_ doesn't work (for me), but that's another story.

**Comment by Midacts** [comment]
I'm running into this as well.
I ran into this trying to use a service principal to connect to O365.

It looks like the MSOnline module is abandonware at this point though?
I'm not sure that the AzureAD has feature parity at this point though.   : [

**Comment by jsypkens** [comment]
We got this to work by using an AD Graph Token instead of MS Graph, with the code below:

$clientId = "(redacted - the app ID from NATIVE app registration in azure AD)";
$tenantId = "company.onmicrosoft.com";
$resourceId = "https://graph.windows.net"
$redirectUri = new-object System.Uri("http://localhost/")

$token = Get-ADALAccessToken -AuthorityName $tenantId -ClientId $clientId -ResourceId $resourceId -UserName $MFAUser -Password $MFAPassword -OutVariable Token
Connect-MsolService -AdGraphAccessToken $token

**Comment by Midacts** [comment]
I am using an AzureAD service principal so i swapped the __'Username'__ and __'Password'__ parameters on the `Get-ADALAccessToken` to __'ClientSecret'__ and it generated a token.

When i run `Connect-MsolService` i get the same/similar error I had been:

```text
An unexpected error occurred.
Exception of type 'Microsoft.Online.Administration.Automation.MicrosoftOnlineException' was thrown.
```

**Comment by delepster** [comment]
Any update on this issue, with MFA being enforced to global admins for CSPs, this is urgent.

**Comment by nukelaser** [comment]
Just ran across this issue as well. This needs to fixed ASAP to keep automated applications/service principals working properly.

**Comment by erSitzt** [comment]
Is this still not working ?

**Comment by Midacts** [comment]
I haven't been able to get it to work.

**Comment by PlanetWilson** [comment]
Same issue here, I really need to be able to connect with an access token of some sort. 

I too decompiled the code in the latest MSOnline module and it now shows:-

`if (Credential == null)
				{
					if (AdGraphAccessToken != null && MsGraphAccessToken != null)
					{
						Logger.Write(LogLevel.Info, "Connect-MsolService", "User provided access token");
						UserSessionState.AccessTokens = new Dictionary<EndPointAlias, string>();
						UserSessionState.AccessTokens.Add(EndPointAlias.AzureAD, AdGraphAccessToken);
						UserSessionState.AccessTokens.Add(EndPointAlias.MSGraph, MsGraphAccessToken);
						UserSessionState.AuthByToken = true;
					}
					else
					{
						Logger.Write(LogLevel.Info, "Connect-MsolService", "Authenticating user interactively");
						UserSessionState.AccessTokens = AuthManager.AuthenticateUser(UserSessionState.AuthenticationContext);
					}`

implying that it requires both tokens?! doesn't sound right...and this is true. When I pass a token now I still get the interactive popup.

**Comment by nukelaser** [comment]
Bad news for anyone who is holding out hope for this. I have been working my way through Microsoft Support for the last five weeks trying to get some kind of definitive answer as to why this switch does not work and when it will be fixed. After three remote sessions I received this email this morning:

> Hi nukelaser,
This is *AGENT* with the Azure AD Developer support team. *PREVIOUS_AGENT* engages our team for further assistance.  The behavior you are seeing is expected and a known issue.  Connect-MSolService will not work with MS Graph Access Token.  This MSOnline PS module is a legacy module and we strongly encourage customer to move to the more modern Azure AD Powershell Module if possible.  With Azure AD Powershell you can call Connect-AzureAD with an MS Graph Access Token (using the -MsAccessToken switch).

...to which I promptly responded and let the agent know that there is a ton of information and functionality that is exclusively available from the MSOnline PowerShell module and that an alternative method of acquiring this information WITHOUT interaction needs to be provided.

I will provide an update as I get more information.

**Comment by midacts** [comment]
I don't really understand why MS would be releasing new services/technology and not have a good way to programmatically manage them.

Maybe its just AzureAD.

**Comment by nukelaser** [comment]
Short version:

The Connect-MsolService cmdlet is never going to work for automation they realize that they do not have any alternatives in place to allow collecting data or executing commands without an interactive sign-in.

Long version:

Here is the next response I received from the support engineer:

>You raised a valid point it’s also something the Product Group is aware of.  Unfortunately MFA status has not been exposed to Graph REST endpoint (it’s what Azure AD PS uses behind the scene).  The PG does have plan to surface this property in the near future (we just don’t have ETA at this point yet). Once the MFA info is exposed the Azure AD PS will be updated to include that information.
 
>Given your business requirement, it does not look like there is a whole lot of options left for you besides using AAD Graph Access token (as I understand this is still working with Connect-MSolService).  Is there any reason what you can not use AAD Graph Access Token instead of MS Graph Access Token?

...to which I reminded them that the AAD Graph access token does not work for the same reason the MS Graph access token does not work. The engineer than admitted that getting the Azure AD Graph access token requires interaction either way so it would not be applicable to this situation:

>In regards to using Azure AD Graph Access token, it’s a little bit tricky to use with Connect-MSolService.  The Access Token has to be a delegated token (authenticating on behalf of a user).  It won’t work if you are using a client credentials flow (authenticating with ClientID and secret) to get an application permission token.

My response:

"So, if I am understanding you correctly, you are saying there is no way to acquire an Azure AD Graph Access Token via non-interactive scripting if all administrative accounts have MFA enabled? Automation more or less becomes impossible if MFA is enabled, for at least with the options that are currently available?"

...and their reply:

>Yes if you enable MFA this will become a problem since you will need some kind of user interaction to respond to that 2nd Factor Authentication.

The engineer than suggested that we simply create an automation account with Global Administrator privileges without MFA enabled and disable interactive sign-ins. I pointed out how this is not an option because of the [partner security requirements](https://docs.microsoft.com/en-us/partner-center/partner-security-requirements-faq) my organization had to adhere to starting August 1st of year, one of the requirements being a baseline protection policy that prevents administrative accounts from being created in our tenant without MFA being applied from the onset. Their response:

>I was suggesting a workaround based on this since you were having issues after enabling MFA.
However, if you are enabling MFA through Baseline policies, then there will be no way to exclude any accounts.

It is possible some new module or feature will be released in the future that will replace these features, but for now...¯\_( ͡⊙ ‿‿ ͡⊙)_/¯

**Comment by XabiBeltza** [comment]
This is ridiculous...

**Comment by isaiahwilliams** [comment]
@XabiBeltza you will be able to do this, but you need to implement the secure application model. Details on this can be found [here](https://docs.microsoft.com/powershell/partnercenter/multi-factor-auth). Please let me know if there are any concerns or questions.

**Comment by delepster** [comment]
> @XabiBeltza you will be able to do this, but you need to implement the secure application model. Details on this can be found [here](https://docs.microsoft.com/powershell/partnercenter/multi-factor-auth). Please let me know if there are any concerns or questions.

We're trying to make this work for a few months now. The only it worked is by using a refresh token, which quite unsuitable for a non-interactive scenario. Do you plans to support non-interactive login complying to the secure application model?

**Comment by isaiahwilliams** [comment]
@delepster since multi-factor authentication will be required for all user accounts in a partner tenant, I am not aware of another solution for the non-interactive scenario. Would you be able to provide insight into why you feel this is not suitable for the non-interactive scenarios?

**Comment by delepster** [comment]
# Requirement
We need a backend service to connect to a tenant with an entity which has global admin rights, to run global-admin-only cmdlets.

# Current Situation
The only way we could make this work is to create a global admin **user** to do so, since neither service principals, nor service accounts could either get connected or run these cmdlets.

**Comment by blalonde** [comment]
To complete @delepster's requirement, we would need to ask the tenant to log in with one of his users and tell him that we will manage his account on the users behalf. This leads to less control over the tenant on our application's behalf since, let's say the tenant deletes his user and forgot that our app was using it, we lose access and need to reprompt him again. In reality, we want him to accept that our application will manage his tenant, not through one of his users but through our application's service principal.

The secure app model requires us to apply the following modifications :
1. Implement a consent window at t0 and explain to the tenant that he needs to log with a user we will "own"
2. Persist the refresh token
3. Implement a refresh token refresh algorithm
4, Implement a re-consent flow in case the user is deleted, password changed, etc.

The service principal flow would enable us to :
1. Implement a consent window at t0 for the tenant to consent to our application

That's it.

**Comment by Wardrop** [comment]
This may not help everyone, but... if you're using conditional access to enforce MFA, you can make exclusions based on say... location (IP address), thereby bypassing the MFA prompt for automated processes from within the company LAN. How I see it, if you're accessing company resources from our company internet connection, then that's as good as one authentication factor. Depends though I guess who you're trying to protect yourself from; external threats, internal threats, or both.

**Comment by billmath** [comment]
Hi

Thank you for your issue submission. Unfortunately, this appears to be a problem with the cmdlt and a support issue. Issues in this repo are for documentation issues. You can try one of the following links for additional help.

Microsoft Support: https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/

Bill
