### ISSUE TITLE
New-AzureADUser has more Required Parameters

### ISSUE THREAD

**Issue by veronicageek** [Azure/azure-docs-powershell-azuread#260]
According to this other Microsoft documentation ([Creating a new user in Azure AD](https://docs.microsoft.com/en-us/powershell/azure/active-directory/new-user-sample?view=azureadps-2.0)), as well as the errors when running the cmdlet in PowerShell, there are **5** mandatory parameters. Not 3.

`-mailNickName` and `-UserPrincipalName` should be moved from optional to **required parameters**.

**Comment by powershellpr0mpt** [comment]
I'm really really curious as to why this hasn't been merged into master yet?
So simple, @veronicageek did all the work in the documentation, the actual cmdlets already throw errors when supplying without UPN & mailnickname.

**Comment by veronicageek** [comment]
Thanks for the shout out @powershellpr0mpt. This module is almost untouched, nevermind maintaining it. Don't even know why it's open source to be honest. So discouraging that I don't submit anymore PR into it, and I'm sure others are in the same state of mind.

**Comment by billmath** [comment]
@veronicageek Thank you for your submission.  Unfortunately, the content in the reference documentation is automatically generated from the source cmdlets.  So this needs to be updated in the source, otherwise, it will get reverted back the next time we do an update.  I have created a work item for this and submitted it to engineering.  But I do not have a timeline on when this might be addressed.   Let me know if you have any additional questions.  At this point I am going to go ahead and close this and will post any updates once i have them.  Thank you!
