### ISSUE TITLE
Connecting to EXO with modern auth

### ISSUE THREAD

**Issue by glennvanrymenant** [Azure/azure-docs-powershell-azuread#293]
Hi

I'm trying to connect to EXO using modern auth without dependency on the available module.

`Add-Type -Path "C:\Program Files\WindowsPowerShell\Modules\AzureAD\2.0.2.16\Microsoft.IdentityModel.Clients.ActiveDirectory.dll"
Add-Type -Path "C:\Program Files\WindowsPowerShell\Modules\AzureAD\2.0.2.16\Microsoft.IdentityModel.Clients.ActiveDirectory.Platform.dll"

$clientID = "a0c73c16-a7e3-4564-9a95-2bdf47383716"
$redirectURI = "urn:ietf:wg:oauth:2.0:oob"
$resourceID = "https://outlook.office365.com/PowerShell-LiveId"
$platformParameters = New-Object "Microsoft.IdentityModel.Clients.ActiveDirectory.PlatformParameters" -ArgumentList "Auto"
$userCredential = New-Object "Microsoft.IdentityModel.Clients.ActiveDirectory.UserCredential" -ArgumentList "<MyUserPrincipalName>"

$authContext = New-Object Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext -ArgumentList "https://login.windows.net/<MyTenantID>/"

$authResult = $authContext.AcquireTokenAsync($resourceID, $clientID, [Uri]$redirectURI, $platformParameters, $userCredential).Result `

On both ADAL 3.18 and 3.19 I'm getting the infamous "Cannot find overload..." error. Can anyone point me in the right direction for doing this? I hope it's possible to get the same kind of connection as by using the module this way (including refresh token).

Thanks!

**Comment by jordanmills** [comment]
Yeah they changed that, as they are wont to do.  I think there are a couple of problems with your code.  The argument for authenticationcontext should have the path of "common" (at least, I couldn't get it to work with what I had).  And the resourceId can't have the path, because the authorization is for the root.  This is what I did to make it work (along with connecting the session):

(Import-Module -Name AzureAD -PassThru) |
ForEach-Object {
    Add-Type -Path "$($_.ModuleBase)\Microsoft.IdentityModel.Clients.ActiveDirectory.dll"
    Add-Type -Path "$($_.ModuleBase)\Microsoft.IdentityModel.Clients.ActiveDirectory.Platform.dll"
}
$resourceID = "https://outlook.office365.com"
$client_id = "a0c73c16-a7e3-4564-9a95-2bdf47383716" # Exchange Online Powershell ID
$redirectURI = "urn:ietf:wg:oauth:2.0:oob" # Redirect URI for Exchange Online
$authContext = [Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext]::new("https://login.windows.net/common/")
$AADcredential = [Microsoft.IdentityModel.Clients.ActiveDirectory.UserCredential]::new()
$platformParameters = [Microsoft.IdentityModel.Clients.ActiveDirectory.PlatformParameters]::new([Microsoft.IdentityModel.Clients.ActiveDirectory.PromptBehavior]::Auto)
$UserID =  [Microsoft.IdentityModel.Clients.ActiveDirectory.UserIdentifier]::AnyUser
$authContext.AcquireTokenAsync($resourceID,$client_id,$redirectURI,$platformParameters,$UserID)
If  (-not $authReply.IsFaulted) {
    $token = $authReply.Result
    $EncodedBasicCredential = [System.Management.Automation.PSCredential]::new($authReply.Result.UserInfo.DisplayableId,(ConvertTo-SecureString -AsPlainText -Force -String ($authReply.Result.AccessTokenType + " " + $authReply.Result.AccessToken)))
    $session = New-PSSession -Name ExchangeOnline -ConnectionUri "$resourceID/PowerShell-LiveId?BasicAuthToOAuthConversion=true" -ConfigurationName Microsoft.Exchange -Credential $EncodedBasicCredential -Authentication Basic
    $session
}

**Comment by billmath** [comment]
Hi @glennvanrymenant

Thank you for your issue submission. Unfortunately, this appears to be a problem with the cmdlt and a support issue. Issues in this repo are for documentation issues. You can try one of the following links for additional help.

Microsoft Support: https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/
