### ISSUE TITLE
SupportsMfa for old domains.

### ISSUE THREAD

**Issue by adrwh** [Azure/azure-docs-powershell-azuread#406]
Hi - the Attribute "SupportsMfa" seems to be "newish".  We setup federation years ago with our IDP and we use MFA, however our "SupportsMfa" attribute is set to $false.

Can you please confirm if we set this to true on a federated domain will NOT have any user imapact?

**Comment by billmath** [comment]
Hi @adrwh 

Thank you for your issue submission.  I have created a work item to track this issue and will be sending it to engineering.  I need to get input into whether this will have any impact because I have never tried this.  At this point, I am going to go ahead and close this issue.  I will post an update as soon as I have any additional information.

Thank you!

Bill
