### ISSUE TITLE
Different results returned when running as user vs as service principal

### ISSUE THREAD

**Issue by jformacek** [Azure/azure-docs-powershell-azuread#424]
When logged in as user and running this cmdlet, it retrieves roles assigned to users, groups, etc. for given application as expected.
However, to get the same result when logged in as service principal, one must call cmdlet Get-AzureADServiceAppRoleAssignedTo

Reproduced on AzureAD module version 2.0.2.76

Also reported earlier on StackOverflow: https://stackoverflow.com/questions/57032543/aad-powershell-command-get-azureadserviceapproleassignment-returned-opposite-r 

Can you look at this one and make note to a docs if it's expected behavior? Looking at graph api, I would say that correct behavior is the one observed when logged in as service principal.

Thank you
Jiri

**Comment by jberezanski-mdg** [comment]
I got bitten by the same issue. From my investigation, the problem seems to be in the underlying Azure AD Graph API (https://graph.windows.net/) the cmdlets call. The newer Microsoft Graph API (https://graph.microsoft.com/) works correctly regardless of the type of the logged on principal and provides the same results as the Azure AD Graph API in the service principal case.

As it seems the Azure AD Graph API is [not actively developed anymore](https://docs.microsoft.com/en-us/previous-versions/azure/ad/graph/api/api-catalog), I doubt it will ever be fixed in that API.
What I would like to see, however, is the AzureAD module switching fully to the MS Graph API (which would fix this issue).

The simple workaround I adopted in my code (which needs to work reliably under both user and service principal context) is to call both Get-AzureADServiceAppRoleAssignment and Get-AzureADServiceAppRoleAssignedTo, union the results and filter based on PrincipalId and ResourceId, depending on the use case.

**Comment by billmath** [comment]
Hi @jformacek 

Thank you for your issue submission.  I have created a work item to track this issue and will be sending it to engineering.  At this point, I am going to go ahead and close this issue.  I will post an update as soon as I have any additional information.

Thank you!

Bill
