### ISSUE TITLE
New-AzureADMSApplication - Example 2 is not current

### ISSUE THREAD

**Issue by wsmelton** [Azure/azure-docs-powershell-azuread#517]
Example 2 does not produce a new app in Azure AD. Tested on AzureAD module version 2.0.2.118.

The error received:

```
New-AzureADMSApplication : Cannot bind parameter 'KeyCredentials'. Cannot create object of type "Microsoft.Open.MSGraph.Model.KeyCredential". Cannot convert the "cert" value of type 
"System.Management.Automation.ScriptBlock" to type "System.Byte[]".
At line:9 char:27
+ ... Credentials @{ KeyId = "11111111-1111-1111-1111-111111111111"; Usage  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-AzureADMSApplication], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.Open.MSGraphV10.PowerShell.NewMSApplication
```

The KeyCredentials and PasswordCredentials do not seem to match proper type.

**Comment by billmath** [comment]
Hi @wsmelton 

I have opened a work item for this so that engineering can take a look and possibly address this.  Unfortunately, these examples are coded in the source and generated automatically, so any updates would get overwritten once we update this again.  We need to get engineering to change this in the code.  At this point, I am going to go ahead and close this issue and will post any update I have here.  Thanks!

Bill
