### ISSUE TITLE
Faulty PowerShell example on Set-AzureADMSPrivilegedRoleSetting.md

### ISSUE THREAD

**Issue by asiantuntija-asiantuntija** [Azure/azure-docs-powershell-azuread#519]
On "azure-docs-powershell-azuread/azureadps-2.0-preview/AzureAD/Set-AzureADMSPrivilegedRoleSetting.md" there's following line:
```   $setting.Setting = "{'required':false}"```

This is incorrectly quoted, I believe it should be:
```   $setting.Setting = '{"required":false}'```

Using example command line is accepted without error, but corrupted JSON data is stored on PIM role configuration afterwards at least when using PS 5.1 on Win10 with latest AzureADPreview module. Trying to view or edit this PIM role via Azure Portal then causes error message on browser javascript debug console and never ending loading screen.

Resulting faulty JSON returned to browser contains has following line:
```   "setting": "('required':false)"```

while it should be:
```   "setting": "(\"required\":false)"```

After doing fix described above, provided example works and changes "JustificationRule" setting as expected. Setting value with proper quoting syntax also solves error on portal side that incorrect syntax causes.

**Comment by billmath** [comment]
Hi @asiantuntija-asiantuntija 

I have opened a work item for this so that engineering can take a look and possibly address this. Unfortunately, these examples are coded in the source and generated automatically, so any updates would get overwritten once we update this again. We need to get engineering to change this in the code. At this point, I am going to go ahead and close this issue and will post any update I have here. Thanks!

Bil
