### ISSUE TITLE
Example missing from get-azureadmsadministrativeunit

### ISSUE THREAD

**Issue by rpstester** [Azure/azure-docs-powershell-azuread#521]
https://docs.microsoft.com/en-us/powershell/module/azuread/get-azureadmsadministrativeunit?view=azureadps-2.0
The example is blank, only has placeholder text.

Suggested example:
get-azureadmsadministrativeunit
Returns all administrative units with their description and DisplayName

**Comment by billmath** [comment]
Hi @rpstester 

I have opened a work item for this so that engineering can take a look and possibly address this. Unfortunately, these examples are coded in the source and generated automatically, so any updates would get overwritten once we update this again. We need to get engineering to change this in the code. At this point, I am going to go ahead and close this issue and will post any update I have here. Thanks!

Bil
