### ISSUE TITLE
Example missing from Add-AzureADMSAdministrativeUnitMember

### ISSUE THREAD

**Issue by rpstester** [Azure/azure-docs-powershell-azuread#522]
https://docs.microsoft.com/en-us/powershell/module/azuread/add-azureadmsadministrativeunitmember?view=azureadps-2.0

The Add-AzureADMSAdministrativeUnitMember cmdlet example 1 is blank, placeholder text only.

Suggested example:
$auid = 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx'
$userid = 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx'
Add-AzureADMSAdministrativeUnitMember -Id $auid -RefObjectId $userid
Adds the given user to the given AU

**Comment by billmath** [comment]
Hi @rpstester 

I have opened a work item for this so that engineering can take a look and possibly address this. Unfortunately, these examples are coded in the source and generated automatically, so any updates would get overwritten once we update this again. We need to get engineering to change this in the code. At this point, I am going to go ahead and close this issue and will post any update I have here. Thanks!

Bil
