### ISSUE TITLE
No Example for New-AzureADMSAdministrativeUnit

### ISSUE THREAD

**Issue by rpstester** [Azure/azure-docs-powershell-azuread#523]
There is no example for New-AzureADMSAdministrativeUnit, only placeholder text.
https://docs.microsoft.com/en-us/powershell/module/azuread/new-azureadmsadministrativeunit?view=azureadps-2.0

Suggested example:
New-AzureADMSAdministrativeUnit -DisplayName "AdminUnit1" -Description "a test AU"
Creates an Admin Unit with given displayname and description

**Comment by billmath** [comment]
Hi @rpstester

I have opened a work item for this so that engineering can take a look and possibly address this. Unfortunately, these examples are coded in the source and generated automatically, so any updates would get overwritten once we update this again. We need to get engineering to change this in the code. At this point, I am going to go ahead and close this issue and will post any update I have here. Thanks!

Bil

**Comment by rpstester** [comment]
Is there a better place I can leave these suggestions, perhaps directly to engineering?
