### ISSUE TITLE
ReadMe Needs massive overhaul

### ISSUE THREAD

**Issue by PsychoData** [Azure/azure-docs-powershell-azuread#534]
One section mentions "Read our [Contributing guidance](CONTRIBUTING.md) to find out more" ([see here](https://github.com/Azure/azure-docs-powershell-azuread/blame/master/README.md#L7)) but the link is dead

In the [Prerequisites section](https://github.com/Azure/azure-docs-powershell-azuread#download) it goes on to tell you to download the "[Docs Authoring Pack](https://marketplace.visualstudio.com/items?itemName=docsmsft.docs-authoring-pack) extension for Visual Studio Code"  - which is missing many of its instruction and screenshots 
![image](https://user-images.githubusercontent.com/3719116/101298315-5b1edb80-37fb-11eb-8a9b-70324692c58a.png)
 
Further instructions on Contributing (Which was already attempted to explain [here](https://github.com/Azure/azure-docs-powershell-azuread#getting-started )- or rather, wasn't) then gets rehashed in the later parts of [Current State of the Repo](https://github.com/Azure/azure-docs-powershell-azuread#current-state-of-repo) 

Per the "current state" there are large portions that are generated and should not be modified, yet there are many Pull Requests being offered for them anyway, which are then manually closed - perhaps there should just be a - for example https://github.com/Azure/azure-docs-powershell-azuread/pull/531 https://github.com/Azure/azure-docs-powershell-azuread/pull/530 https://github.com/Azure/azure-docs-powershell-azuread/pull/526 https://github.com/Azure/azure-docs-powershell-azuread/pull/524  and the list goes on. Perhaps a bot or Continuous Integration item could just close out Pull Requests, or Fail them when they try to write to generated areas of the code, since those are not outlined clearly

As it is, it's very confusing for a user to load up the repository or Docs page, look over the readme, get told to visit a non-existent file, get told to use a tool with a broken introduction, instructed to go through a third page that explains how to use the previous tool, get down to the end of the readme document, after spending an hour or more trying to figure out how to contribute to the documentation and improve it, only to realize that large portions of the Repo are generated, and the edits they  came to make are not going to be used. 

By the way, I looked through 82 Problems for just the file I was suggesting changes on from the Docs Markdown Linter - and none of them warned I was trying to make a commit to change generated code that shouldn't be changed here - if you're going to be suggesting the Docs Linter be used to lint these, you should probably look at making this one of the [rules it applies](https://github.com/DavidAnson/markdownlint/blob/v0.22.0/doc/Rules.md)  or defining a [CustomRule](https://github.com/DavidAnson/markdownlint/blob/v0.22.0/doc/CustomRules.md#custom-rules)  to stop the commits there. 

Several options to keep nice, helpful people from wasting their time trying to make useful edits to the Docs pages where they will just be rejected later on

**Comment by billmath** [comment]
@PsychoData 

I totally agree. I have created a work item for this but it probably will not be addressed until after the holidays.  I have some feature release work that is due prior to a vacation and this repo could use a dedicated engineer.  Unfortunately I have other areas I also work on and I don't see that changing anytime soon.  Anyway, our first goal is to streamline the process so that doc errors can be updated.  This module doesn't benefit from some of the automation other PowerShell modules do, so some of the features in those repos are not an option.  I am engaging engineering to either get source code access so I can make the changes myself or see what other viable options are available.  Another idea is to make the module totally open-source and then changes could be made directly there, but I am not sure if this an option.

I do like your idea of putting something in place on the repo to prevent PRs from being created against the auto-generated code.  I am going to make inquiries about this.   I have been a writer for awhile, but I am fairly new to repo management, so I am not as familiar with all of the features and functionality that can be done.  Any suggestions would be great and thank you for the feedback.

Bill
