### ISSUE TITLE
 Remove-AzureADUserAppRoleAssignment lacks example code

### ISSUE THREAD

**Issue by leehowarth** [Azure/azure-docs-powershell-azuread#535]
The docs for  Remove-AzureADUserAppRoleAssignment currently lacks any concrete examples and currently has a placeholder for example code to be inserted. 

https://docs.microsoft.com/en-us/powershell/module/azuread/remove-azureaduserapproleassignment?view=azureadps-2.0

**Comment by leehowarth** [comment]
Please note a PR was created for this issue but I was asked to open an issue instead to allow the correct process to be followed. 

https://github.com/Azure/azure-docs-powershell-azuread/pull/506

**Comment by billmath** [comment]
Hi @leehowarth 

I have opened a work item for this so that engineering can take a look and possibly address this. Unfortunately, these examples are coded in the source and generated automatically, so any updates would get overwritten once we update this again. We need to get engineering to change this in the code. At this point, I am going to go ahead and close this issue and will post any update I have here. 

But any issue you run in to, keep these coming because the more work items I open, the quicker we are to getting a fix.

Thanks!

Bill

**Comment by LegiaScouser** [comment]
@billmath Hey Bill how can a guy/gal pull the -AppRoleAssignmentID to pipe it into this Remove command if the Getter doesn't fetch it!? 😄 thanks!

**Comment by mbendana** [comment]
@LegiaScouser 

You may be able to use this one:

Get-AzureADUserAppRoleAssignment -ObjectId <USER_OBJECT_ID_GOES_HERE> | % { Remove-AzureADUserAppRoleAssignment -ObjectId $_.PrincipalId -AppRoleAssignmentId $_.ObjectId }

**Comment by LegiaScouser** [comment]
@mbendana holy wow!

**Comment by LegiaScouser** [comment]
@mbendana 

Remove-AzureADUserAppRoleAssignment : Error occurred while executing RemoveUserAppRoleAssignment 
Code: Request_BadRequest
Message: The request URI is not valid. Since the segment 'Microsoft.DirectoryServices.User' refers to a collection, this must be the last segment in the request URI. All intermediate segments must refer to a single resource.

    + CategoryInfo          : NotSpecified: (:) [Remove-AzureADUserAppRoleAssignment], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.AzureAD16.Client.ApiException,Microsoft.Open.AzureAD16.PowerShell.RemoveUserAppRoleAssignment

**Comment by LegiaScouser** [comment]
it would be amazing if there was a powershell example for this.
https://docs.microsoft.com/en-us/users/register?redirectUrl=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fgraph%2Fapi%2Fuser-list-approleassignments%3Fview%3Dgraph-rest-1.0%26tabs%3Dhttp%23example-1-list-approleassignments-granted-to-a-user

**Comment by mbendana** [comment]
@LegiaScouser 

Then, you'll have to do something like:

$arrayOfUserObjectIdsVariable | % {Get-AzureADUserAppRoleAssignment -ObjectId $_ } | % { Remove-AzureADUserAppRoleAssignment -ObjectId $.PrincipalId -AppRoleAssignmentId $.ObjectId }

**Comment by LegiaScouser** [comment]
@mbendana thank you so much you saved my day :D
