### ISSUE TITLE
Add EmailAsAlternateId to Staged Rollout options

### ISSUE THREAD

**Issue by calvinlui** [Azure/azure-docs-powershell-azuread#537]
Opening a new issue as instructed in #489.

Staged Rollout support for EmailAsAlternateId was added in [AzureADPreview 2.0.2.117](https://www.powershellgallery.com/packages/AzureADPreview/2.0.2.117).

**Comment by billmath** [comment]
Hi @calvinlui 

I have opened a work item for this so that engineering can take a look and possibly address this. Unfortunately, these examples are coded in the source and generated automatically, so any updates would get overwritten once we update this again. We need to get engineering to change this in the code. At this point, I am going to go ahead and close this issue and will post any update I have here.

But any issue you run in to, keep these coming because the more work items I open, the quicker we are to getting a fix.

Thanks!

Bill
