### ISSUE TITLE
incorrect sample at https://github.com/Azure/azure-docs-powershell-azuread/blob/live/azureadps-2.0/AzureAD/Get-AzureADApplicationPasswordCredential.md

### ISSUE THREAD

**Issue by SeanXuMSFT** [Azure/azure-docs-powershell-azuread#539]
the link https://github.com/Azure/azure-docs-powershell-azuread/blob/live/azureadps-2.0/AzureAD/Get-AzureADApplicationPasswordCredential.md is for get-azureadapplicationpasswordcredential cmdlet, but the sample in the documetn is with New-AzureADApplicationPasswordCredential, which cause confusion for customer

**Comment by billmath** [comment]
Hi @SeanXuMSFT 

I have opened a work item for this so that engineering can take a look and possibly address this. Unfortunately, these examples are coded in the source and generated automatically, so any updates would get overwritten once we update this again. We need to get engineering to change this in the code. At this point, I am going to go ahead and close this issue and will post any update I have here.

But any issue you run in to, keep these coming because the more work items I open, the quicker we are to getting a fix.

Thanks!

Bill
