### ISSUE TITLE
Filter parameter for Get-AzureADUser cmdlet does not accept all OData operators

### ISSUE THREAD

**Issue by wiseleaf23** [Azure/azure-docs-powershell-azuread#542]
The filter parameter for the Get-AzureADUser cmdlet does not handle all OData operators as specified at https://www.odata.org/documentation/odata-version-3-0/odata-version-3-0-core-protocol/#queryingcollections. For example the following command works:
`Get-AzureADUser -Filter "startswith(JobTitle,'Sales')"`
And the following does not:
`Get-AzureADUser -Filter "endswith(JobTitle,'Sales')"`

I tested some variations, and most do not seem to work as documented by OData. The second command will return
```Get-AzureADUser : Error occurred while executing GetUsers 
Code: Request_UnsupportedQuery
Message: Unsupported Query.
RequestId: 022ca9b2-2db4-4d4b-ab45-9fff8433abab
DateTimeStamp: Tue, 15 Dec 2020 15:49:18 GMT
HttpStatusCode: BadRequest
HttpStatusDescription: Bad Request
HttpResponseStatus: Completed
At line:1 char:1
+ Get-AzureADUser -Filter "endswith(JobTitle,'Sales')"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzureADUser], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.AzureAD16.Client.ApiException,Microsoft.Open.AzureAD16.PowerShell.GetUser
```

**Comment by billmath** [comment]
@wiseleaf23 

I have opened a work item for this so that engineering can take a look and possibly address this. Unfortunately, these examples are coded in the source and generated automatically, so any updates would get overwritten once we update this again. We need to get engineering to change this in the code. At this point, I am going to go ahead and close this issue and will post any update I have here. Thanks!

Bill
