### ISSUE TITLE
Issue with documentation

### ISSUE THREAD

**Issue by nromyn** [Azure/azure-docs-powershell-azuread#556]
I was directed to open an issue instead of creating a PR here:
https://github.com/Azure/azure-docs-powershell-azuread/pull/240

Non-rendering characters are present in the help file, and should be cleaned up.
> this application by default will use the �Default� connector group in your tenant.

**Comment by billmath** [comment]
@nromyn 

I have opened a work item for this so that engineering can take a look and possibly address this. Unfortunately, these examples are coded in the source and generated automatically, so any updates would get overwritten once we update this again. We need to get engineering to change this in the code. At this point, I am going to go ahead and close this issue and will post any update I have here. Thanks!

Bill
