### ISSUE TITLE
New-AzureADApplicationKeyCredential Example 2: Use a certificate to add an application key credential

### ISSUE THREAD

**Issue by baoguoca** [Azure/azure-docs-powershell-azuread#557]
`New-AzureADApplicationKeyCredential -ObjectId $keyid -CustomKeyIdentifier $base64Thumbprint -Type AsymmetricX509Cert -Usage Verify -Value $base64Value -StartDate $cer.GetEffectiveDateString() -EndDate $cer.GetEx........................`

The `$keyid `as `-ObjectId` is not correct here since  `$keyid ` is a random guid.
If we pass `$keyid` here, we will get  _**Request_ResourceNotFound**_.

Possible solution: 
Add one more parameter `-KeyId` to receive `$keyid ` from local.

**Comment by billmath** [comment]
@baoguoca 

I have opened a work item for this so that engineering can take a look and possibly address this. Unfortunately, these examples are coded in the source and generated automatically, so any updates would get overwritten once we update this again. We need to get engineering to change this in the code. At this point, I am going to go ahead and close this issue and will post any update I have here. Thanks!

Bill
