### ISSUE TITLE
Get-AzureADAuditSignInLogs doesn't return non-interactice sign-ins (AzureADPreview 2.0.2.129)

### ISSUE THREAD

**Issue by jimmyth68** [Azure/azure-docs-powershell-azuread#574]
When using Get-AzureADAuditSignInLogs to retrieve sign-ins for a specific account, it only returns interactive sign-ins.
I compare the output with the output from the GUI in the sign-ins section for an account, where you can toggle between interactive and non-interactive sign-ins.

I have also tried to explicitly specify "IsInteractive eq $False" but when doing so the cmdlet returns an error "Invalid filter clause".

I don't know if it's related but when checking the page for the sign-in api, "IsInteractive" is not among the supported attributes for the $filter parameter: [https://docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-1.0&tabs=http]

**Comment by toddalbers** [comment]
Is this issue being addressed?  jimmyth68 submitted this on Feb 23, 2021.  It is now June 06, 2021 and I see the same issue.  I understand that Get-AzureADAuditSignInLogs is part of AzureADPreview.  However, the [documentation for Get-AzureADAuditSignInLogs](https://docs.microsoft.com/en-us/powershell/module/azuread/get-azureadauditsigninlogs?view=azureadps-2.0-preview)  doesn't mention anything about this.  This is a security weakness in Azure because Admins relying on  Get-AzureADAuditSignInLogs results will likely assume that all sign-ins are included when they are not.  The functionality is there though.  We know this because non-interactive logs show up on a separate tab [on the User Sign-Ins page ](https://aad.portal.azure.com/#blade/Microsoft_AAD_IAM/UsersManagementMenuBlade/SignIns) in the Azure console.  I also tried to use the isInteractive filter but it returns no results even though there are nonInteractive records in the User SignIn Logs:  

- Get-AzureADAuditSignInLogs -Filter "isInteractive eq $false"

 Can someone provide the name of the function and\or info on how to pull non-interactive logs via PowerShell?

**Comment by besiler** [comment]
@msewaweru can you assign this to me?

**Comment by msewaweru** [comment]
@jimmyth68 - apologies that we have not been able to get back to you with a solution to your issue. Since this module is planned for deprecation, most of the investments are focused on Microsoft Graph PowerShell. I would recommend that you check out the available alternative in Microsoft Graph PowerShell using [Get-MgAuditLogSignIn](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.reports/get-mgauditlogsignin?view=graph-powershell-1.0). If you require further support on this issue, you can try one of the following links for additional help.
Microsoft Support: https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/

I will proceed to close this issue. Feel free to open follow-up doc-related issues here.
