### ISSUE TITLE
Get-AzureADMSPrivilegedResource -ProviderId AzureResource no longer lists Subscription Object

### ISSUE THREAD

**Issue by frazhamid** [Azure/azure-docs-powershell-azuread#584]
cmdlet Get-AzureADMSPrivilegedResource -ProviderId AzureResources no longer lists the Subscription as a type.

e.g. $Subscription = Get-AzureADMSPrivilegedResource -ProviderId AzureResources | Where-Object {$_.DisplayName -eq $SubscriptionName}

This was quite useful for me, as I would use the resource ID to configure all the role settings in line with the business requirements e.g. approvals, activation limits etc.

# Get the script user to supply the Azure Subscription name
$SubscriptionName = Read-Host "Please enter the subscription display name"
$Subscription = Get-AzureADMSPrivilegedResource -ProviderId AzureResources | Where-Object {$_.DisplayName -eq $SubscriptionName}

# Get the role resource and role settings
$RoleName = $RoleToConfigure.Name
$Role = Get-AzureADMSPrivilegedRoleDefinition -providerid AzureResources -ResourceId $Subscription.Id  | Where-Object {$_.DisplayName -eq $RoleName}

$RoleSettings = Get-AzureADMSPrivilegedRoleSetting -ProviderId 'AzureResources' -Filter "ResourceId eq '$($Subscription.Id)'" | Where-Object {$_.RoleDefinitionId -eq $Role.Id}

**Comment by shaunsat** [comment]
This is the same for me, I wrote a load of scripts sometime ago and was wondering why they suddenly stopped working

**Comment by msewaweru** [comment]
@frazhamid - Apologies that we have not gotten back to you with a solution to this issue. Due to the planned deprecation of this module, all investments are in the [Microsoft Graph PowerShell](https://learn.microsoft.com/en-us/powershell/microsoftgraph/overview?view=graph-powershell-1.0) module. I recommend that you try [Get-MgPrivilegedAccessResource](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.identity.governance/get-mgprivilegedaccessresource?view=graph-powershell-beta) which is the alternative cmdlet in Microsoft Graph. 
If you require further support on this issue, you can try one of the following links for additional help.
Microsoft Support: https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/

I will proceed to close this issue. Feel free to open follow-up doc-related issues here.
