### ISSUE TITLE
AzureAD Module disabled on June 30th, 2022 ?

### ISSUE THREAD

**Issue by felickz** [Azure/azure-docs-powershell-azuread#589]
Is the AzureAD powershell module going to be no longer functional after the AzureAD Graph goes offline on June 30th, 2022?

Ref: https://docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-planning-checklist
` Important
Azure AD Graph API is now deprecated. We will continue to provide technical support and security updates but will no longer provide feature updates. Starting June 30th, 2022, we will end support for Azure AD Graph and will no longer provide technical support or security updates. Apps using Azure AD Graph after this time will no longer receive responses from the Azure AD Graph endpoint. 
`

**Comment by Gill-Bates** [comment]
I love the cmdlet `Get-AzureADUser`, because it will deliver plenty of information:

![image](https://user-images.githubusercontent.com/25774289/113137728-34126c80-9225-11eb-86ef-2ebf7d9128c2.png)

When I perform the same with` Get-AzADUser`, I will receive only some basic information. **Bug or feature?**

![image](https://user-images.githubusercontent.com/25774289/113137910-6f14a000-9225-11eb-824b-c8de39ae6bfe.png)

**Comment by robertcaretta** [comment]
Interested in this thread.

**Comment by msewaweru** [comment]
@kimaniderrick, please see this.

**Comment by kimaniderrick** [comment]
For applications that are yet to migrate from AAD graph by June 2022, we will have an exception and will communicate as time goes on our plans.

**Comment by msewaweru** [comment]
Hello @felickz, please take note of the comment by @kimaniderrick. I will proceed to close this issue. Feel free to reopen it should you have any follow up feedback.
