### ISSUE TITLE
General Docs Update - Is the AzureAD PowerShell Module Abandonware?

### ISSUE THREAD

**Issue by aydeisen** [Azure/azure-docs-powershell-azuread#621]
If I go by the documents currently published for the AzureAD module, I would come to the conclusion that the AzureAD module is abandonware.

- The [version history document](https://docs.microsoft.com/powershell/azure/active-directory/ad-pshell-v2-version-history?view=azureadps-2.0) hasn't been updated since June 2020, with the last version being 2.0.2.105
- The published version in the PowerShell Gallery is older than what's published in the version history
- There's no published roadmap to move these cmdlets from legacy .NET Framework to .NET 5+
- There is no published GitHub repo for this module, as there is with every other Azure and Azure Graph related cmdlet (this module points to Microsoft Docs as the project site)
- While not as intuitive as the AzureAD modules, the [Microsoft.Graph PowerShell SDK](https://docs.microsoft.com/graph/powershell/get-started) has all of the above addressed, and appears to be poised to replace the AzureAD module

If I perform a Find-Module in PowerShell, I do see the latest GA version of the module to be 2.0.2.135, and the latest version of the preview module to be 2.0.2.136, both with a publish date of a month ago.  However, with the aforementioned issue about the documentation and roadmaps, I have no insight into what has actually changed between the ~30 revisions between the last document update and this version.

With all of the above, the only two conclusions I can see are that the AzureAD modules are abandonware, or there's some inside-politicking happening that is causing the AzureAD PowerShell Module to stand out as secluding itself from the visibility Microsoft has provided for all of its other Azure and Microsoft Graph related PowerShell projects.  If it's the latter, I want no part of Microsoft's internal strifes impacting the software I depend on for my own work.

If it's the former, can someone at least update the documentation to point to the new Microsoft Graph for PowerShell SDK project?

**Comment by msewaweru** [comment]
@aydeisen, thanks for these issues. Here are my responses;
- For the version history page, we have updated it with changes from the most recent release and we will ensure to update it as new releases are done. We will also endeavor to highlight the changes in the 7 Azure AD and 6 Preview modules that have been missed in the past.
- The GitHub repo for this module is [Azure AD PowerShell](https://github.com/Azure/azure-docs-powershell-azuread).
- There is work going into the Microsoft.Graph PowerShell SDK documentation to make it more user friendly.

We are now actively working to improve the documentation for Azure AD PowerShell because this module is not abandonware.
I hope this answers your question. I will proceed to close this issue. Feel free to reopen it if you have any further concerns.

**Comment by aydeisen** [comment]
@msewaweru 

Thanks for your reply.  Just one question remains outstanding:

What's the roadmap to make the AzureAD module compatible with Powershell 7?

**Comment by msewaweru** [comment]
Hello @aydeisen, I will follow up with the team to find this out. I will let you know once I do.

**Comment by aydeisen** [comment]
@msewaweru 

Thank you.  I appreciate the team's effort to bring all of this documentation up to date

**Comment by msewaweru** [comment]
Hi @aydeisen. This is to let you know Azure AD PowerShell will not updated to work with PowerShell 7. To get more info on the current and future investments please see [this blogpost](https://techcommunity.microsoft.com/t5/azure-active-directory-identity/automate-and-manage-azure-ad-tasks-at-scale-with-the-microsoft/ba-p/1942489).
