### ISSUE TITLE
Get-AzureADApplicationOwner - ErrorAction Preference does not take effect

### ISSUE THREAD

**Issue by rajaprad** [Azure/azure-docs-powershell-azuread#65]
### Cmdlet:
 Get-AzureADApplicationOwner 

### Module version
AzureAD 2.0.0.71  

### Description

The error action preference to ignore does not take effect in the command.

PS C:\Windows\system32> Get-AzureADApplicationOwner -ObjectId 89c71197-aa21-4043-8112-**-ErrorAction SilentlyContinue**
Get-AzureADApplicationOwner : Error calling GetApplicationOwners:
{"odata.error":{"code":"Request_ResourceNotFound","message":{"lang":"en","value":"Resource
'89c71197-aa21-4043-8112-' _does not exist or one of its queried reference-property objects are not
present_."}}}
At line:1 char:1
+ Get-AzureADApplicationOwner -ObjectId 89c71197-aa21-4043-8112-...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzureADApplicationOwner], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.AzureAD16.Client.ApiException,Microsoft.Open.AzureAD16.PowerShell.GetAppl
   icationOwners

**Comment by RobdeJong** [comment]
This is probably true for all AzureAD V2 cmdlets, we’re investigating this and will get back to this soon.

Thanks,

Rob

**Comment by TaraMeyer** [comment]
@RobdeJong is investigating the issue.

**Comment by RobdeJong** [comment]
Bug created for PowerShell team

**Comment by TaraMeyer** [comment]
@RobdeJong - thank you for the update!

**Comment by mrkeiths** [comment]
Hello,
Is there any update about intentions to correct this defect?

Since there are no cmdlets to test whether Connect-AzureAD has been called, I test connectivity myself using _Get-AzureADTenantDetail **-ErrorAction 'SilentlyContinue'** -ErrorVariable err_, then interrogate $err to see if the underlying exception is AadNeedAuthenticationException.

Since AzureAD cmdlets appear to be ignoring the PowerShell design principals that allow us to indicate error handling preferences, users of my script will see error messages regardless.

I will test try/catch then redirecting the error stream next but these potential workarounds shouldn't be necessary.

I'm piling on to this thread since the reported issue seems the same but I can open a new issue if preferred... please just let me know.

Thank you,
Keith

**Comment by billmath** [comment]
This looks like it has been resolved.
