### ISSUE TITLE
Set-MsolDeviceRegistrationServicePolicy -AllowedToAzureAdJoin Selected gives error

### ISSUE THREAD

**Issue by AlyaKoni** [Azure/azure-docs-powershell-azuread#694]
Loaded Modules:
MSOnline 1.1.183.57
AzureADPreview 2.0.2.138

Running the following cmdlet:
`Set-MsolDeviceRegistrationServicePolicy -AllowedToAzureAdJoin Selected -Users $AlyaAllowedUsers -Groups $AlyaAllowedGroups`
$AlyaAllowedUsers is set to a Microsoft.Online.Administration.User
$AlyaAllowedGroups is set o a Microsoft.Online.Administration.Group

I get the error:
object reference not set to an instance of an object

Full trace in german:
Set-MsolDeviceRegistrationServicePolicy : Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
In Zeile:3 Zeichen:5
+     Set-MsolDeviceRegistrationServicePolicy -AllowedToAzureAdJoin $se ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [Set-MsolDeviceRegistrationServicePolicy], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.Online.Administration.Automation.SetDeviceRegistrationService 
   Policy

**Comment by msewaweru** [comment]
Hello @AlyaKoni, thanks for your issue submission and apologies for the delayed response.

I will ask @spunukol to advise on the best way to provide the run this Set cmdlet.

**Comment by msewaweru** [comment]
Hi @myra-ramdenbourg, reassigning this issue to you.

**Comment by msewaweru** [comment]
@AlyaKoni - apologies that we have not been able to get back to you with a solution to your issue. Since this module is planned for deprecation, most of the investments are focused on [Microsoft Graph PowerShell](https://learn.microsoft.com/en-us/powershell/microsoftgraph/overview?view=graph-powershell-1.0) and we are in the process of building parity for this cmdlet. 

For further support on this issue, you can try one of the following links:
Microsoft Support: https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/

I will proceed to close this issue. Feel free to open follow-up doc-related issues here.
