### ISSUE TITLE
Different behavior for Get-AzureADServiceAppRoleAssignedTo and Get-AzureADServiceAppRoleAssignment based on auth type?

### ISSUE THREAD

**Issue by ztrhgf** [Azure/azure-docs-powershell-azuread#766]
I've noticed that these two cmdlets (Get-AzureADServiceAppRoleAssignedTo and Get-AzureADServiceAppRoleAssignment) behave differently (probably) because of auth. type I use to connect AzureAD.

<img_ width="887" alt="image" src="https://user-images.githubusercontent.com/2930419/151140033-3128d3ef-5e0a-48b3-a719-a4922a91a866.png">

The left console is authenticated using a global admin **user**. The right console is authenticated using **service principal** with global reader and security reader roles (same result when global admin role is added).

**Comment by psignoret** [comment]
First, I _strongly_ encourage you to use [Microsoft Graph PowerShell](https://docs.microsoft.com/graph/powershell/get-started), where this type of issue is addressed.

Second, you are correct: the API that these cmdlets call has a peculiar behavior which is dependent on whether the module is connected using a Microsoft-owned app registration (e.g. the default identity for Azure AD PowerShell), or using a customer-owned app or service identity (e.g. an app registration, or a managed identity). We have a pending documentation update which will clarify this with some examples.

In the meantime, this should help get you going:

* When connected with a Microsoft-owned app identity (i.e. the default when running `Connect-AzureAD`):
  * In `(Get|New|Remove)-AzureADServiceAppRoleAssignment`, `-ObjectId` is the object ID of the _resource_ app's service principal—the service principal which exposes the app roles assigned (to a user, group, or other service principal).
  * In `Get-AzureADServiceAppRoleAssignedTo`, `-ObjectId` is the object ID of the assigned principal—the client service principal which was granted an app role (which we also call "application permission", when it's granted to another service principal).
* When connected with a customer-owned app identity (e.g. when connecting with a service principal, or by passing an access token obtained separately):
  * In `(Get|New|Remove)-AzureADServiceAppRoleAssignment`, `-ObjectId` is the object ID of the assigned service principal—the _client_ app's service principal, which is granted an app role assignment (application permission).
  * In `Get-AzureADServiceAppRoleAssignedTo`, `-ObjectId` is the object ID of the resource app's service principal——the service principal which exposes the app roles that will be assigned (to a user, group, or other service principal).
* Regardless of how you're connected:
  * In `(Get|New|Remove)-AzureADUserAppRoleAssignment`, `-ObjectId` identifies the assigned principal—the user granted the app role assignments.
  * In `(Get|New|Remove)-AzureADUserAppRoleAssignment`, `-ObjectId` identifies the assigned principal—the group granted the app role assignments.

Again, you should _really_ consider using Microsoft Graph PowerShell instead of Azure AD PowerShell, for this. This bizarre behavior doesn't exist in Microsoft Graph.
