### ISSUE TITLE
Remove-AzureADServiceAppRoleAssignment is not working as expected / is still using old API

### ISSUE THREAD

**Issue by magic-happenz** [Azure/azure-docs-powershell-azuread#782]
Hello,

trying to use this cmdlet I noticed that it isn´t doing what it´s supposed to in our environment. Instead of removing the service app role assignment, it just removes the granted consent, the permission however remains on the app and users that have permission for example can still give new consent. Is this intended? And if yes, what is the correct command to remove the app role assignment instead?

I also noticed that it is still using graph.windows.net in the background which is not only deprecated for two years, it´s also end of life in about 4 months so this might be related? I am sure that is not the only command that still uses it so I am wondering what the future of this module is? 

Best,
Mario

**Comment by msewaweru** [comment]
Hello @magichappens89 , this cmdlet removes the assignment of a certain app role from either a user, group or service principal. The role itself remains defined on the resource but the assignment to either a user, group or service principal is removed and you reassign it afresh. Let me know if this is what you also want to remove.

You are right. This cmdlet still calls the Azure AD Graph endpoint. We are currently working on official communication on the way forward with the deprecation. We however recommend that you start migrating to [Microsoft Graph PowerShell](https://docs.microsoft.com/en-us/powershell/microsoftgraph/overview?view=graph-powershell-1.0) which is where all efforts are focused in order to achieve parity with the Azure AD PowerShell.

**Comment by magichappens89** [comment]
Hello @msewaweru , 

I think it actually manages service principal assignment. For the assignment of users and groups there are other cmdlets. What I want is that the app permissions assignment is removed (as indicated by the cmdlet name). However it just removes admin consent if there was any.
![image](https://user-images.githubusercontent.com/63111919/155135948-ea764b5a-a0a9-47fc-b0e5-8b650c3be344.png)

Based on the architecture I guess this is rather something that needs to be done on the app registration but the module lacks cmdlets for this.
It seems that there is no command of archiving this, also not in the Microsoft Graph PowerShell module. Hope you can advise how to actually remove it.

**Comment by msewaweru** [comment]
@psignoret , could you help with this query.

@magichappens89 , there could be an extension for users to continue using Azure AD PowerShell for sometime and this communication will be going out to you as soon as it is finalized.

**Comment by magichappens89** [comment]
@msewaweru, there could? Any ETA when this communication will be finalized? I am a bit confused. I mean the Azure AD PowerShell was "the" module to administer Azure AD with PowerShell. A lot of the commands stop working in 4 months because of the end of life I guess. And there is still yet no communication or whatsoever how to migrate etc?

**Comment by msewaweru** [comment]
@magichappens89, the ETA for his communication should be March and that will be to say that the cmdlets will not stop working in 4 months. The plan is to give customers more time to migrate by providing the migration tools and guidance to Microsoft Graph PowerShell.

**Comment by magichappens89** [comment]
@msewaweru but how the modules that use Azure AD graph can still work after the API will be end of life?

**Comment by psignoret** [comment]
@magichappens89

*Regarding the API*:

I suggest you consider the API used by this module to be mostly an implementation detail. If Microsoft says the module is still supported, then it doesn't really matter if the API the module relies on is supported for use by your own applications. That said, you [_should_](https://techcommunity.microsoft.com/t5/azure-active-directory-identity/automate-and-manage-azure-ad-tasks-at-scale-with-the-microsoft/ba-p/1942489) be actively working on switching to Microsoft Graph PowerShell, and you should not write any new scripts using Azure AD PowerShell.

*Regarding the `Remove-AzureADServiceAppRoleAssignment`* cmdlet:

This cmdlet removes app role assignments, but it sounds like this isn't what you expect it to do. Can you clarify what you expected this cmdlet to do?

An app role assignment is an association between a service principal representing an app or a service (the "resource"), and a user, a group, or a service principal for another app or service (the "principal"), representing authorization granted for the principal to access the resource. App roles which can be assigned to service principals, are sometimes called "application permissions".

The table from your screenshot (from Azure portal > Azure AD > App registrations > API permissions) includes two bits of information:

1. The list of API permissions (delegated permissions and app roles) the application is configured to require. This is just a "wishlist" of the permissions you'd _like_ the application to have, primarily used to inform consent experiences. If you want to remove a configured permission, you would update the *RequiredResourceAccess* property of the Application object (i.e. the app registration). Here's an example:

   ```powershell
   # Remove required permissions for Microsoft Graph from required API permission, keep the rest
   $myAppId = "{my-app-id}"
   $graphAppId = "00000003-0000-0000-c000-000000000000"
   $app = Get-MgApplication -Filter "appId eq '$($myAppId)'"
   $newRra = @(,$app.RequiredResourceAccess | ? { $_.ResourceAppId -ne $graphAppId })
   Set-MgApplication -ApplicationId $app.Id -RequiredResourceAccess $newRra
   ```

   Keep in mind, that removing a permission from this list *does not* revoke a permission *grant*. If you remove a required permission which was granted, it will still be granted.

2. The list of API permissions which have been *granted* to the application. These are the tenant-wide delegated permission grants and app role assignments which have actually been granted to the application. To remove a delegated permission grant, you would use `Remove-MgOAuth2PermissionGrant`. To remove an app role assignment you would use `Remove-MgServicePrincipalAppRoleAssignedTo`. Here's an example:

   ```powershell
   # Remove all Microsoft Graph app role assignments granted to this app
   $myAppId = "{my-app-id}"
   $graphAppId = "00000003-0000-0000-c000-000000000000"
   $sp = Get-MgServicePrincipal -Filter "appId eq '$($myAppId)'"
   $graph = Get-MgServicePrincipal -Filter "appId eq '$($graphAppId)'"
   Get-MgServicePrincipalAppRoleAssignment -ServicePrincipalId $sp.Id -Filter "resourceId eq $($graph.Id)" | % {
       Remove-MgServicePrincipalAppRoleAssignedTo -ServicePrincipalId $graph.Id -AppRoleAssignmentId $_.Id
   }
   ```

The examples above are using Microsoft Graph PowerShell because that's what you should be switching to. Here are the equivalent examples, using Azure AD PowerShell:

```powershell
# Remove required permissions for Microsoft Graph from required API permission, keep the rest
$myAppId = "{my-app-id}"
$graphAppId = "00000003-0000-0000-c000-000000000000"
$app = Get-AzureADApplication -Filter "appId eq '$($myAppId)'"
$newRra = @(,$app.RequiredResourceAccess | ? { $_.ResourceAppId -ne $graphAppId })
Set-AzureADApplication -ObjectId $app.ObjectId -RequiredResourceAccess $newRra
```

```powershell
# Remove all Microsoft Graph app role assignments granted for this app
$myAppId = "{my-app-id}"
$graphAppId = "00000003-0000-0000-c000-000000000000"
$sp = Get-AzureADServicePrincipal -Filter "appId eq '$($myAppId)'"
$graph = Get-AzureADServicePrincipal -Filter "appId eq '$($graphAppId)'"
Get-AzureADServiceAppRoleAssignedTo -ObjectId $sp.ObjectId | ? { $_.ResourceId -eq $graph.ObjectId } | % {
    Remove-AzureADServiceAppRoleAssignment -ObjectId $graph.ObjectId -AppRoleAssignmentId $_.ObjectId
}
```

<sub>Note: Use of `Get-AzureADServiceAppRoleAssignedTo` in the example above assumes you connected with the default use of `Connect-AzureAD`, without connecting with a customer-owned app or service.</sub>

**Comment by magichappens89** [comment]
@psignoret thank you for that detailed answer. That confirms the workaround I assumed working as well. I was just trying to find a command to remove the application permission without changing the required resource access object and `Remove-AzureADServiceAppRoleAssignment` cmdlet seemed the right choice for me. However, running this only removes the admin consent granted for that assignment.
Before
![image](https://user-images.githubusercontent.com/63111919/155360311-15e9fc9d-f9f6-4606-a972-0daf120ca6c3.png)
After
![image](https://user-images.githubusercontent.com/63111919/155360446-f1c49d06-adb0-4da7-b9da-f077833ed8d5.png)
I understood that to remove the actual resource permission I need `Set-AzureADApplication`. I will take a look at Microsoft Graph PowerShell module as well. Thank you.

**Comment by magichappens89** [comment]
@psignoret I just tried out the Microsoft Graph PowerShell commands you provided. Remove all Microsoft Graph app role assignments granted to this app works for me. Although I found "assignments" in this context confusing as the assignments are the actual permissions for me in this context. 
`Set-MgApplication` did not work as there is no cmdlet with that name. Also tried it with `Update-MgApplication`  but that runs into an error.
`Cannot process argument transformation on parameter 'RequiredResourceAccess'. Cannot convert the 
"Microsoft.Graph.PowerShell.Models.IMicrosoftGraphRequiredResourceAccess[]" value of type "Microsoft.Graph.PowerShell.Models.IMicrosoftGraphRequiredResourceAccess[]" to type
"Microsoft.Graph.PowerShell.Models.IMicrosoftGraphRequiredResourceAccess".`

**Comment by wenjun001** [comment]
unsubscribe

**Comment by msewaweru** [comment]
@Jackson-Woods , are you able to help with this query?

**Comment by msewaweru** [comment]
@magic-happenz, please see the latest updates on the deprecations plans [here](https://docs.microsoft.com/en-us/powershell/azure/active-directory/overview?view=azureadps-2.0).
