### ISSUE TITLE
New-AzureADMSNamedLocationPolicy errors out when you include Kosovo (XK)

### ISSUE THREAD

**Issue by telnet25** [Azure/azure-docs-powershell-azuread#807]
Creating any new policy using New-AzureADMSNamedLocationPolicy where if the parameter  "-CountriesAndRegions" has Kosovo included, powershell throws an error where it says it 'cannot convert value "XK" to type
"Microsoft.Open.MSGraph.Model.CountriesAndRegion". Error: "Unable to match the identifier name XK to a valid
enumerator name. Specify one of the following enumerator names and try again'.

![image](https://user-images.githubusercontent.com/70075187/163827980-744f7591-7219-4e25-b03e-d22bd2c8fd85.png)

This has been tested in both AzureAD and AzureADPreview.

ON GUI: You can actually see Kosovo and click it when creating a new named location policy. If you get that policy using powershell with Get-AzureADMSNamedLocationPolicy, it will throw another error pertaining to Kosovo (XK) as well.

**Comment by msewaweru** [comment]
Hello @telnet25 for highlighting this issue. I will gather more info on this issue and get back to you on it.

**Comment by msewaweru** [comment]
Hi @davidspooner, is this something you can help with?

**Comment by msewaweru** [comment]
Hello @telnet25, thanks for highlighting this issue and apologies for the delayed response. I would like to confirm that we were able to reproduce this issue which is a result of a required update in the Azure AD PowerShell module. However all the PowerShell efforts are currently invested in the Microsoft Graph PowerShell module. I have tested that I'm able to accomplish the tasks you mentioned above successfully in Microsoft Graph PowerShell. I would therefore urge to use this module to run your tasks esp because Azure AD PowerShell is headed for deprecation and take time to try out [Microsoft Graph PowerShell](https://docs.microsoft.com/en-us/powershell/microsoftgraph/overview?view=graph-powershell-1.0).

**Comment by jordanmills** [comment]
> Hello @telnet25, thanks for highlighting this issue and apologies for the delayed response. I would like to confirm that we were able to reproduce this issue which is a result of a required update in the Azure AD PowerShell module. However all the PowerShell efforts are currently invested in the Microsoft Graph PowerShell module. I have tested that I'm able to accomplish the tasks you mentioned above successfully in Microsoft Graph PowerShell. I would therefore urge to use this module to run your tasks esp because Azure AD PowerShell is headed for deprecation and take time to try out [Microsoft Graph PowerShell](https://docs.microsoft.com/en-us/powershell/microsoftgraph/overview?view=graph-powershell-1.0).

Last I checked, there was no way to do this through Graph.  How were you able to accomplish that task?

**Comment by msewaweru** [comment]
Hi @allenrg , @jordanmills, please note that this issue shall not be fixed in Azure AD PowerShell module as it's planned for deprecation. You can successfully run this using [Microsoft Graph PowerShell](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.identity.signins/new-mgidentityconditionalaccessnamedlocation?view=graph-powershell-1.0&preserve-view=true). See below what I can do in Graph PowerShell.
