### ISSUE TITLE
Error converting value "linux" to type when using Get-AzureADMSConditionalAccessPolicy

### ISSUE THREAD

**Issue by byteben** [Azure/azure-docs-powershell-azuread#812]
Using cmdlet Get-AzureADMSConditionalAccessPolicy results in an error if the Conditional Access policy includes "linux" in the Device Platform filter.

Get-AzureADMSConditionalAccessPolicy : Error converting value "linux" to type
'Microsoft.Open.MSGraph.Model.ConditionalAccessDevicePlatforms'. Path
'value[10].conditions.platforms.excludePlatforms[4]'

**Comment by msewaweru** [comment]
Hello @byteben and thank you for raising this issue. Please allow me to get the right person that can help with this. Thanks.

**Comment by tsceif** [comment]
I'm also having the same issue.

**Comment by PeterDeThier-MSFT** [comment]
I am running into this as well...

With Linux checked in a CA policy the Get-AzureADMSConditionalAccessPolicy command fails:

![image](https://user-images.githubusercontent.com/104528648/167655879-af40b420-a28c-47c7-84be-7ec5de2be5e2.png)

![image](https://user-images.githubusercontent.com/104528648/167655787-a3b5ab94-7410-4e53-b2e2-892d4fe38f7f.png)

With Linux unchecked in the CA policy it succeeds:

![image](https://user-images.githubusercontent.com/104528648/167656049-d737eb2f-cf31-44ef-92af-a0829d63c2e1.png)

**Comment by MWPatterson2000** [comment]
Watching this as I am having same issue

**Comment by byteben** [comment]
> Hello @byteben and thank you for raising this issue. Please allow me to get the right person that can help with this. Thanks.

Thanks @davidspooner for picking this up

**Comment by davidspooner** [comment]
Thanks everyone for the interest in Conditional Access PowerShell and raising the issue.  Due to the planned deprecation of PowerShell modules (MSOL & AAD) after December 2022, no further updates are planned for these modules to support new Conditional Access features. See recent announcements for more information: https://aka.ms/AzureADPowerShellDeprecation. As a result of this, newer Conditional Access features may not be available or may not be functional within these PowerShell modules as a result of this announcement. Please consider migrating to Microsoft Graph PowerShell (https://aka.ms/MigrateMicrosoftGraphPowerShell). Additional guidance and examples will be released soon and will replace the current Azure AD PowerShell examples.
