### ISSUE TITLE
Setting for notifications

### ISSUE THREAD

**Issue by DevanshuSyk** [Azure/azure-docs-powershell-azuread#828]
Hello is there a setting for customizing the  role notification setting in 
[Set-AzureADMSPrivilegedRoleSetting (AzureADPreview)] .None of the parameter talk about updating notification setting

**Comment by DevanshuSyk** [comment]
no one has any idea?

**Comment by msewaweru** [comment]
Hi @DevanshuSyk, apologies for the delayed response.

@psignoret, please confirm is this cmdlet falls in your area and advise.

**Comment by msewaweru** [comment]
Hi @DevanshuSyk - Apologies that we have not come back to you with a solution in such a long time.

Due to the planned deprecation of the Azure AD PowerShell, all our investments are in the [Microsoft Graph PowerShell](https://learn.microsoft.com/en-us/powershell/microsoftgraph/overview?view=graph-powershell-1.0) module, which is recommended for use. I recommend that you try this setting update using the Update-MgPolicyRoleManagementPolicy cmdlet. Use [the example on this page](https://learn.microsoft.com/en-us/graph/api/unifiedrolemanagementpolicy-update?view=graph-rest-beta&tabs=powershell) to do the update. 

Proceeding to close this issue. Feel free to open doc related issues here,
