### ISSUE TITLE
What role needed for connect-azureAD with CBA?  sample code fails

### ISSUE THREAD

**Issue by peternwilliams** [Azure/azure-docs-powershell-azuread#837]
https://github.com/Azure/azure-docs-powershell-azuread/blob/main/azureadps-2.0/AzureAD/Connect-AzureAD.md has sample code to configure Connect-AzureAD. I don't have a role with the objectID of 5997d714-c3b5-4d5b-9973-ec2f38fd49d5.  I chenaged to 107859fd-2ca6-4bd9-ade9-16357947f802 (Directory Writers) and am functional.

Running the following line generates an error:
Add-AzureADDirectoryRoleMember -ObjectId 5997d714-c3b5-4d5b-9973-ec2f38fd49d5 -RefObjectId $sp.ObjectId
Add-AzureADDirectoryRoleMember : Error occurred while executing AddDirectoryRoleMember 
Code: Request_ResourceNotFound
Message: Resource '5997d714-c3b5-4d5b-9973-ec2f38fd49d5' does not exist or one of its queried reference-property objects are not present.
RequestId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx
DateTimeStamp: Thu, 30 Jun 2022 17:52:07 GMT
HttpStatusCode: NotFound
HttpStatusDescription: Not Found
HttpResponseStatus: Completed
At line:1 char:1
+ Add-AzureADDirectoryRoleMember -ObjectId 5997d714-c3b5-4d5b-9973-ec2f ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-AzureADDirectoryRoleMember], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.AzureAD16.Client.ApiException,Microsoft.Open.AzureAD16.PowerShell.AddDirectoryRoleMember
 
Someone else got this too according to https://issueantenna.com/repo/Azure/azure-docs-powershell-azuread/issues/827

**Comment by msewaweru** [comment]
@DerrickJKimani, is this something you can advise on or direct me to the right person?

**Comment by msewaweru** [comment]
@peternwilliams - Apologies for the delay in getting back to you on this issue. For the resource ensure that the directory role exists before assigning a member. Once you have determined the directory roles available, you can assign a new member. See below: 
<img width="673" alt="image" src="https://github.com/Azure/azure-docs-powershell-azuread/assets/73849846/452f478e-94a4-4eca-b7ec-d50bf7f37064">

Also, due to the planned deprecation of this module, I recommend that you try Microsoft Graph PowerShell, which has an alternative cmdlet to achieve this.

<img width="1117" alt="image" src="https://github.com/Azure/azure-docs-powershell-azuread/assets/73849846/b146dc81-113c-4524-91a6-4281d02e80a0">

I will proceed to close this issue. Feel free to open any doc-related issue here.
