### ISSUE TITLE
Get-AzureADMSConditionalAccessPolicy fails if Linux is specified as an included or excluded platform in the Device Platforms Conditions in any Conditional Access Policy

### ISSUE THREAD

**Issue by Martin-Day** [Azure/azure-docs-powershell-azuread#846]
When running Get-AzureADMSConditionalAccessPolicy, an error is shown if any conditional access policies have a device platform condition set that includes or excludes Linux as a platform. 

Conditional Access Policy Config:
![image](https://user-images.githubusercontent.com/53221043/181585450-6688e1c4-6ef3-48da-969b-3a54388d49d6.png)

Error Message:
![image](https://user-images.githubusercontent.com/53221043/181585656-f47d896b-7f4e-4fe6-a977-2c193b8725b9.png)

This occurs with both AzureAD and AzureADPreview modules.

AzureAD module version being used:
![image](https://user-images.githubusercontent.com/53221043/181585985-86c3fb23-9579-49f5-ba58-3071959f696a.png)

**Comment by msewaweru** [comment]
Hello @Martin-Day - Thanks for raising the issue. Due to the planned deprecation of PowerShell modules (MSOnline & Azure AD), no further updates are planned for these modules to support new Conditional Access features. See recent announcements for more information [here](https://aka.ms/AzureADPowerShellDeprecation). As a result of this, newer Conditional Access features may not be available or may not be functional within these PowerShell modules as a result of this announcement. Please consider migrating to [Microsoft Graph PowerShell](https://aka.ms/MigrateMicrosoftGraphPowerShell). Additional guidance and examples will be released soon and will replace the current Azure AD PowerShell examples.
