### ISSUE TITLE
Get-AzureADMSConditionalAccessPolicy : Error converting value "linux" to type

### ISSUE THREAD

**Issue by SuryenduB** [Azure/azure-docs-powershell-azuread#855]
Get-AzureADMSConditionalAccessPolicy
Get-AzureADMSConditionalAccessPolicy : Error converting value "linux" to type 
'Microsoft.Open.MSGraph.Model.ConditionalAccessDevicePlatforms'. Path 'value[1].conditions.platforms.excludePlatforms[3]', line   
1, position 2270.
At line:1 char:1
+ Get-AzureADMSConditionalAccessPolicy
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzureADMSConditionalAccessPolicy], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.MSGraphBeta.Client.ApiException,Microsoft.Open.MSGraphBeta.PowerShell.GetAzureADMSC  
   onditionalAccessPolicy

**Comment by msewaweru** [comment]
Thanks @SuryenduB for the interest in Conditional Access PowerShell and raising the issue. Due to the planned deprecation of PowerShell modules (MSOL & AAD) after December 2022, no further updates are planned for these modules to support new Conditional Access features. See recent announcements for more information: [Change management](https://aka.ms/AzureADPowerShellDeprecation). As a result of this, newer Conditional Access features may not be available or may not be functional within these PowerShell modules as a result of this announcement. Please consider migrating to Microsoft Graph PowerShell (https://aka.ms/MigrateMicrosoftGraphPowerShell). Additional guidance and examples will be released soon and will replace the current Azure AD PowerShell examples.
