### ISSUE TITLE
Linux device platform type not recognized for Get-AzureADMSConditionalAccessPolicy

### ISSUE THREAD

**Issue by anpiskai** [Azure/azure-docs-powershell-azuread#858]
Get-AzureADMSConditionalAccessPolicy returns an error when there are any policies that contain an explicit inclusion or exclusion for the Linux device type. The GUI and Microsoft Graph both work fine, however, the cmdlet does not.

This is the error returned
<img width="1223" alt="image" src="https://user-images.githubusercontent.com/48796638/191026468-a832c02c-e0e3-41d4-9f78-680589f84444.png">

Here is the working configuration in Graph and the GUI.
<img width="544" alt="image" src="https://user-images.githubusercontent.com/48796638/191026621-c5a23fcc-1018-4b08-91bb-b800ca85c035.png">
<img width="425" alt="image" src="https://user-images.githubusercontent.com/48796638/191026594-93d5a4c7-e06e-49c5-9deb-14103cbe3e48.png">

<img width="225" alt="image" src="https://user-images.githubusercontent.com/48796638/191026742-8357193b-0b30-4e54-8bd6-c7bd02c2fcff.png">

**Comment by msewaweru** [comment]
Thanks @anpiskai  for raising the issue. Due to the planned deprecation of PowerShell modules (MSOL & Azure AD) after December 2022, no further updates are planned for these modules to support new Conditional Access features. See recent announcements for more information: [Change management](https://aka.ms/AzureADPowerShellDeprecation). As a result of this, newer Conditional Access features may not be available or may not be functional within these PowerShell modules as a result of this announcement. Please consider migrating to Microsoft Graph PowerShell (https://aka.ms/MigrateMicrosoftGraphPowerShell).
