### ISSUE TITLE
`Set-AzureADApplication` - several descriptions not populated in the .md or .yaml files

### ISSUE THREAD

**Issue by bubbletroubles** [Azure/azure-docs-powershell-azuread#992]
In the `Set-AzureADApplication` documentation, there are several descriptions which are not populated. Is this something that needs to be updated upstream as these files are auto-generated, or should the descriptions be populated in this repo?

[Set-AzureADApplication.md - line 467 - {{ Fill IsDisabled Description }}](https://github.com/Azure/azure-docs-powershell-azuread/blob/0ca53d42c1087cb22f50a281486cf179a9c4f93d/azureadps-2.0/AzureAD/Set-AzureADApplication.md?plain=1#L467)

[Set-AzureADApplication.md - line 407 - {{ Fill AllowPassthroughUsers Description }}](https://github.com/Azure/azure-docs-powershell-azuread/blob/0ca53d42c1087cb22f50a281486cf179a9c4f93d/azureadps-2.0/AzureAD/Set-AzureADApplication.md?plain=1#L407)

[Set-AzureADApplication.yml - line 180 - {{ Fill IsDisabled Description }}](https://github.com/Azure/azure-docs-powershell-azuread/blob/0ca53d42c1087cb22f50a281486cf179a9c4f93d/azureadps-2.0/AzureAD/Set-AzureADApplication.yml#L180)

**Comment by csmulligan** [comment]
@bubbletroubles thank you so much for pointing this out. Since the Azure AD PowerShell module is deprecated, we’re no longer updating this documentation. We recommend transitioning to the new Microsoft Graph PowerShell module, where we are actively working to address this type of issue in the documentation. 
Please find more information about the deprecation [here.](https://techcommunity.microsoft.com/t5/microsoft-entra-blog/important-update-deprecation-of-azure-ad-powershell-and-msonline/ba-p/4094536)
I'll go ahead and close this issue. Please feel free to reach out to us again if you need any assistance. 
Thanks again!
#please-close
